name: github_search
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk:  ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  github_search_library:
    path: ../github_search_library
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
