name: github_search_library
description: library for logic and ui separation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  http: ^1.2.2
  stream_transform: ^2.0.0
